services:
  ors-map:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    working_dir: "/ors"
    command: [ "java", "-jar", "ors.jar" ]

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "target/app.jar"]
    volumes:
      - uploads:/uploads
    env_file:
      - .env

volumes:
  uploads: